
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>MEnu Usuarios</title>
<link rel="stylesheet" type="text/css" href="../css/estilo.css" />

</head>
<body background="../imagenes/Imagen fondo aurora celeste.png">

	
</header>
<h1>Men&uacute; de Unidades</h1>
<div class="curved loginn" >
<table width="100%">
<tr>
<td>
<a href="../index.php?accion=addunidad">
<img src="../imagenes/User - Resource.png"width="128" height="128" alt="">
</a>
<br>Ingresar Unidad
</td>
<td>
<a  href="../index.php?accion=verunidad">
<img src="../imagenes/editar.jpg" width="128" height="128" alt="">
</a>
<br>Ver Unidad
</td>
</tr>
</table>

</div>
<div  align="center">
      <p align="center"><a href="../formularios/plantillaA.php" target="_self" tabindex="4" class="otro">Regresar</a> 
  </div>
</body>
</html>

<ul>
<li><a href="<?php echo Conectar::ruta();?>?accion=index">Home</a></li>
<li><a href="<?php echo Conectar::ruta();?>?accion=veruser" title="idhorario"> Id Horario </a><li>
<li><a href="<?php echo Conectar::ruta();?>?accion=adduser" title="fecha-hora-salida"> Fecha-Hora-Salida </a><li>
<li><a href="<?php echo Conectar::ruta();?>?accion=adduser" title="fecha-hora-regreso"> Fecha-Hora-Regreso </a><li>
</ul>

